// global styles here
import { StyleSheet, Dimensions } from 'react-native';

export default StyleSheet.create({
  container:{
    backgroundColor:'rgba(0,0,0,0.5)',
    paddingHorizontal:20,
    justifyContent:'center',
    flex:1
  },
  content:{
    backgroundColor:'#090f2e',
  },
  icon:{
    width:25,
    height:25,
    resizeMode:'contain'
  },
  text:{
    fontSize:8,
    color:'white',
    textAlign:'center'
  },
  topRow:{
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'flex-end',
    height:60,
    backgroundColor:'#151a37',
    padding:10
  },
  item:{
    justifyContent:'center',
    alignItems:'center',
    width:50
  },
  wrapLogo:{
    alignItems:'center',
    position:'absolute',
    alignSelf:'center',
    top:-20,
  },
  logo:{
    width:60,
    height:60,
    resizeMode:'contain'
  },
  topView:{
    marginTop:20
  },
  row:{
    flexDirection:'row',
    alignItems:'center',
    height:60,
    backgroundColor:'#151a37',
    padding:10,
    marginTop:3
  },
  rightItem:{
    flex:1,
    alignItems:'center',
    justifyContent:'center'
  },
  rightItemText:{
    fontSize:10,
    color:'white',
  },
  row1:{
    flexDirection:'row',
    alignItems:'center',
    height:60,
    marginTop:3
  },
  leftView:{
    flexDirection:'row',
    alignItems:'center',
    flex:1,
    backgroundColor:'#151a37',
    height:'100%',
    paddingLeft:10,
  },
  rightView:{
    height:'100%',
    width:75,
    alignItems:'center',
    justifyContent:'center',
    marginLeft:3,
    backgroundColor:'#151a37',
  },
  rightItemText1:{
    fontSize:9,
    color:'white',
  },
  noteWrap:{
    marginTop:3,
    backgroundColor:'white',
    padding:10
  },
  note:{
    fontSize:12,
    color:'#5e627a'
  },
  btnText:{
    color:'white',
    marginTop:3,
    textAlign:'center',
    fontSize:8,
    backgroundColor:'transparent'
  },
  btnIcon:{
    width:30,
    height:30,
    resizeMode:'contain'
  },
  bottomView:{
    height:60,
    backgroundColor:'#939497',
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'space-around'
  },
  name:{
    color:'white',
    marginTop:3,
    textAlign:'center',
    backgroundColor:'transparent',
    fontSize:10
  },
  button:{
    alignItems:'center'
  }
})
