// global styles here
import { StyleSheet, Dimensions } from 'react-native';

export default StyleSheet.create({
  container:{
    flex:1,
    backgroundColor:'#090f2e',
  },
  topView:{
    paddingHorizontal:10,
    paddingVertical:20,
    backgroundColor:'#151b3f'
  },
  leftView:{
    width:100,
    alignItems:'center'
  },
  row:{
    flexDirection:'row'
  },
  title:{
    fontSize:12,
    textAlign:'center',
    color:'white'
  },
  content:{
    flexDirection:'row',
    marginTop:20
  },
  icon:{
    width:40,
    height:40,
    resizeMode:'contain',
  },
  text:{
    fontSize:11,
    color:'white'
  },
  listWrap:{
    flexDirection:'row',
    paddingHorizontal:10,
    paddingVertical:20,
  },
  arrowIcon:{
    width:15,
    height:15,
    resizeMode:'contain',
    margin:10
  },
  item:{
    flexDirection:'row',
    alignItems:'center',
    marginTop:10
  },
  square:{
    width:10,
    height:10,
    marginRight:10
  },
  bottomView:{
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'center',
    alignSelf:'center',
    marginVertical:10,
  },
  button:{
    height:44,
    width:44,
    borderRadius:22,
    backgroundColor:'#939598',
    alignItems:'center',
    justifyContent:'center',
    marginHorizontal:10
  },
  buttonText:{
    fontSize:7,
    textAlign:'center',
    color:'white'
  },
})
