import dashboard from './Dashboard';
import eventDetail from './EventDetail';
import eventConfirm from './EventConfirm';
import listOfChats from './ListOfChats';
import activitySearch from './ActivitySearch';
import startAClub from './StartAClub';
import myClub from './MyClub';
import addActivity from './AddActivity';
import profile from './Profile';
import activityMap from './ActivityMap';
import myBookmarks from './MyBookmarks';
import setLocation from './SetLocation';
import eventSummary from './EventSummary';
import inviteModal from './InviteModal';
import activities from './ActivitiesList';
import setDateTime from './SetDateTime';
import clubs from './Clubs';
import startClubConfirm from './StartClubConfirm';
import postActivity from './PostActivity';
import rightMenu from './RightMenu';
import faq from './Faq';
import myGallery from './MyGallery';
import clubProfileToJoin from './ClubProfileToJoin';
import clubProfileHost from './ClubProfileHost';
import clubEvents from './ClubEvents';
import manageClub from './ManageClub';
import members from './Members';
import chooseCategory from './ChooseCategory';

export const Dashboard = dashboard;
export const EventDetail = eventDetail;
export const EventConfirm = eventConfirm;
export const ListOfChats = listOfChats;
export const ActivitySearch = activitySearch;
export const StartAClub = startAClub;
export const MyClub = myClub;
export const AddActivity = addActivity;
export const Profile = profile;
export const ActivityMap = activityMap;
export const MyBookmarks = myBookmarks;
export const SetLocation = setLocation;
export const EventSummary = eventSummary;
export const InviteModal = inviteModal;
export const Activities = activities;
export const SetDateTime = setDateTime;
export const Clubs = clubs;
export const StartClubConfirm = startClubConfirm;
export const PostActivity = postActivity;
export const RightMenu = rightMenu;
export const Faq = faq;
export const MyGallery = myGallery;
export const ClubProfileToJoin = clubProfileToJoin;
export const ClubProfileHost = clubProfileHost;
export const ClubEvents = clubEvents;
export const ManageClub = manageClub;
export const Members = members;
export const ChooseCategory = chooseCategory;
