// global styles here
import { StyleSheet, Dimensions } from 'react-native';

export default StyleSheet.create({
  container:{
    flex:1,
    backgroundColor:'#00072c',
  },
  swithView:{
    height:30,
    width:180,
    backgroundColor:'#151a40',
    flexDirection:'row',
    alignSelf:'center',
    marginTop:20,
    borderRadius:3
  },
  item:{
    flex:1,
    alignItems:'center',
    justifyContent:'center'
  },
  itemText:{
    fontSize:10,
    color:'#676b76'
  },
  selectedItem:{
    backgroundColor:'#06ab4b',
    borderRadius:3
  },
  selectedItem1:{
    backgroundColor:'#bb1f4c',
    borderRadius:3
  },
  selectedText:{
    color:'white'
  },
  datePicker: {
      borderRadius:3,
      backgroundColor:'white',
      height:30,
      paddingVertical:0,
      paddingHorizontal: 0,
      marginTop:20,
      width: '100%'
  },
  picker:{
      borderRadius:3,
      backgroundColor:'white',
      height:30,
      paddingVertical:0,
      paddingHorizontal:10,
      marginTop:20
  },
  input:{
    borderRadius:3,
    backgroundColor:'white',
    height:30,
    paddingVertical:0,
    paddingHorizontal:10,
    marginTop:20,
    fontSize:10,
    textAlign:'center'
  },
  content:{
    flex:1,
    width:180,
    alignSelf:'center',
    marginBottom:20
  },
  icon:{
    width:80,
    height:40,
    resizeMode:'contain',
    alignSelf:'center',
    marginBottom:20,
  },
  dropdown:{
    position:'absolute',
    top:51,
    left:0,
    right:0,
    backgroundColor:'white',
    zIndex:999
  },
  text:{
    fontSize:10,
    paddingVertical:10,
    textAlign:'center',
    borderBottomWidth:0.5,
    borderColor:'#ddd'
  },
  btnDropdown:{
    borderRadius:3,
    backgroundColor:'white',
    height:30,
    paddingVertical:0,
    paddingHorizontal:10,
    marginTop:20,
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'center'
  },
  btnDropdownText:{
    fontSize:10,
    textAlign:'center',
    color:'#5e627a'
  },
  indicator:{
    color:'#5e627a',
    fontSize:15,
    position:'absolute',
    top:5,
    right:10
  }
})
