// global styles here
import { StyleSheet, Dimensions } from 'react-native';
const wrapSize = 150
const padding = 20

export default StyleSheet.create({
  container:{
    flex:1,
    backgroundColor:'#090f2e',
  },
  content:{
    flex:1,
    alignItems:'center',
    justifyContent:'center'
  },
  form:{
    flexDirection:'row',
    marginHorizontal:10
  },
  inputs:{
    flex:1,
    marginRight:10
  },
  rightView:{
    width:40,
    height:130,
    borderRadius:25,
    backgroundColor:'#939497',
    alignItems:'center',
    justifyContent:'center'
  },
  buttonIcon:{
    width:30,
    height:30,
    resizeMode:'contain',
    marginVertical:6
  },
  text:{
    color:'white',
    fontSize:8,
    textAlign:'center',
    marginTop:5
  },
  imageBottom:{
    width:100,
    height:40,
    alignSelf:'center',
    marginVertical:10,
    resizeMode:'contain'
  },
  input:{
    borderRadius:3,
    backgroundColor:'white',
    height:30,
    paddingVertical:0,
    paddingHorizontal:10,
    flex:1,
    marginTop:5,
  },
  mainContent:{
    width:220,
    height:220,
  },
  imageBorder:{
    flex:1,
    width:null,
    height:null,
  },
  avatar:{
    width:80,
    height:80,
    position:'absolute',
    top:70,
    left:70
  },
  text1:{
    width:100,
    color:'white',
    fontSize:10,
    textAlign:'right',
    position:'absolute',
    top:0,
    left:0,
  },
  text2:{
    width:100,
    color:'white',
    fontSize:10,
    textAlign:'right',
    position:'absolute',
    top:20,
    left:0,
  },
  text3:{
    width:100,
    color:'white',
    fontSize:10,
    textAlign:'right',
    position:'absolute',
    top:40,
    left:0,
  },
  btnHide:{
    width:40,
    height:40,
    borderRadius:20,
    backgroundColor:'#430423',
    alignItems:'center',
    justifyContent:'center',
    position:'absolute',
    top:-44,
    right:0
  },
  buttontext:{
    color:'white',
    fontSize:7,
    textAlign:'center',
  },
  editPhoto:{
    color:'white',
    fontSize:10,
    textAlign:'center',
    position:'absolute',
    bottom:20,
    left:0,
    right:0
  }
})
