// global styles here
import { StyleSheet, Dimensions } from 'react-native';

export default StyleSheet.create({
  container:{
    flex:1,
    backgroundColor:'#00072c',
  },
  swithView:{
    height:30,
    width:180,
    backgroundColor:'#151a40',
    flexDirection:'row',
    alignSelf:'center',
    marginTop:10,
    borderRadius:3
  },
  item:{
    flex:1,
    alignItems:'center',
    justifyContent:'center'
  },
  itemText:{
    fontSize:10,
    color:'#676b76'
  },
  selectedItem:{
    backgroundColor:'#06ab4b',
    borderRadius:3
  },
  selectedItem1:{
    backgroundColor:'#bb1f4c',
    borderRadius:3
  },
  selectedText:{
    color:'white'
  },
  input:{
    borderRadius:3,
    backgroundColor:'white',
    height:30,
    paddingVertical:0,
    paddingHorizontal:10,
    marginTop:20,
    fontSize:10,
    textAlign:'center'
  },
  picker:{
      borderRadius:3,
      backgroundColor:'white',
      height:30,
      paddingVertical:0,
      paddingHorizontal:10,
      marginTop:20
  },
  content:{
    width:180,
    alignSelf:'center',
    marginBottom:20
  },
  icon:{
    width:80,
    height:40,
    resizeMode:'contain',
  },
  btnProceed:{
    alignSelf:'center',
    marginBottom:20,
    marginTop:20
  },
  text:{
    fontSize:10,
    textAlign:'center',
    color:'white',
    marginTop:10
  },
  bottomText:{
    fontSize:10,
    textAlign:'center',
    color:'white',
    marginTop:10,
    marginBottom:20,
    width:150,
    alignSelf:'center'
  }
})
